# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSI-Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KSI-Task

    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'RealmSwift', '~> 10.40.1'
    pod 'Kingfisher', '~> 7.10'
    pod 'Alamofire'
    pod 'MBProgressHUD', '~> 1.2'
end
